### ISSUE TITLE
libusb_dyn.c is missing stubs for several of the libusb-win32 functions

### ISSUE THREAD

**Issue by mcuee** [mcuee/libusb-win32#13]
Updated: 2012-08-09 Created: 2012-05-20 Creator: Benjamin Moody

libusb_dyn.c is missing stubs for several of the libusb-win32 functions:
```
usb_touch_inf_file_np
usb_install_needs_restart_np
usb_install_npW
usb_install_npA
usb_reap_async_nocancel
usb_cancel_async
```

(It's also missing the various _rundll stubs, but I doubt there's any point in including those.)

The first four are related to driver installation, and any program that uses those will probably want to link to libusb0.dll directly. But usb_reap_async_nocancel and usb_cancel_async should at least be included.

(I'm trying to compile a program (tilem) that links to a library (libticables2) that links to libusb (and uses those two functions), but my program doesn't currently make use of the USB features of libticables2, so I would like to avoid the libusb0.dll dependency if possible.)

Patch is attached; I have not tested it beyond making sure it compiles, but it's pretty straightforward.

**Comment by mcuee** [comment]
libusb-win32 project is in a support only mode. Mailing list support is still provided, no changes to the codes and release.

**Comment by dontech** [comment]
FIXED
