### ISSUE TITLE
How to get usb position info？

### ISSUE THREAD

**Issue by ltaini** [mcuee/libusb-win32#15]
Hello，i have two questions。
One is why create device like '\\.\libusb0-0001' is succeed?Is this device defined in register or just defined by libusb?
The other is how i can get the detail information of usb position?In this format:Port_#0002.Hub_#0002?
Thanks.

**Comment by mcuee** [comment]
Please use libusb-win32 mailing list for technical support. The github site is for issue reporting and feature enhancement proposal.
