### ISSUE TITLE
libusb-win32 driver to uninstall?

### ISSUE THREAD

**Issue by ShiverZm** [mcuee/libusb-win32#18]
sometime there are some crash,with the device self driver,so i need to uninstall  it when i never use libusb-win32 driver,anything can help?

**Comment by mcuee** [comment]
I am not so sure what you mean by self driver. If you mean the filter driver, use the filter driver wizard to uninstall. If you use the device driver, you can uninstall by using the following utility.
https://github.com/lostindark/DriverStoreExplorer
