### ISSUE TITLE
Support ARM64

### ISSUE THREAD

**Issue by dontech** [mcuee/libusb-win32#29]
Going forward, the ARM64 platform will become more popular.
Update the system to support building this target.

**Comment by mcuee** [comment]
Yes this is a good idea. ARM64 will get more and more important down the road.

FYI, there is a request to support ARM64 for Zadig as well.
https://github.com/pbatard/libwdi/issues/155

**Comment by mcuee** [comment]
So there is a potential issue how to get the driver installer working without Zadig and libusbk-inf-wizard.

**Comment by mcuee** [comment]
This issue can be closed now that #40 and #41 have been merged.
