### ISSUE TITLE
Port to later WDK.

### ISSUE THREAD

**Issue by dontech** [mcuee/libusb-win32#30]
Current SDK supported is WIN7 WDK, which is getting a bit old.

**Comment by mcuee** [comment]
Yes this is a good idea. I think we need to drop Windows XP/Vista support and then set the minimum OS requirement to Windows 7.

In that case, we can use the latest Windows 11 WDK.
https://docs.microsoft.com/en-us/windows-hardware/drivers/download-the-wdk

**Comment by mcuee** [comment]
@dontech If you want to keep the build script, Enterprise WDK (EWDK) may be considered.
https://docs.microsoft.com/en-us/windows-hardware/drivers/download-the-wdk

**Comment by dontech** [comment]
mcuee, you read my mind. Already looking at switching to win11 DDK, and dropping xp/vista support.

**Comment by mcuee** [comment]
This can be closed now that #40 and #41 have been merged.
