### ISSUE TITLE
Nothing Registers anymore

### ISSUE THREAD

**Issue by fritz2k** [mcuee/libusb-win32#31]
Since I installed this nothing I plug in like USBs Gamepads or Mics dont work anymore, I get the connected sound but they dont pop up.

**Comment by mcuee** [comment]
That should not happen unless you use the old version of libusb-win32 or you install the class filter. It should not happen if you use the device driver option (only for single device) or even the device filter option (only for single device). 

How do you install the libusb-win32?

**Comment by mcuee** [comment]
Close for now due to no updates. Please reopen once you are able to provide more info.
