### ISSUE TITLE
libusb-win32 libusb.a for Codeblocks 20.03

### ISSUE THREAD

**Issue by booyasdr** [mcuee/libusb-win32#32]
I would like to compile my code with the GNU GCC compiler that comes with Codeblocks 20.03. I get an error that says "skipping incopatible" libusb.a, that uses to work. They says that happens when there is a 32/64 bit incompatibility. How can I get a 64 bit libusb.a that will link? I am using libusb-win32 1.2.6.0 with function calls usb_bulk_setup_async(),  usb_submit_async(), usb_reap_async().

**Comment by mcuee** [comment]
You should be able to import libusb0.dll using MinGW GCC. libusb-win32 has provided both 32bit/64bit DLL.

Take note we do not support building from source the DLL using MinGW GCC, rather you should import the DLL and dynamically link to the libusb0.dll. You can ask the CodeBlock community or MinGW GCC comunity how to do that.

**Comment by mcuee** [comment]
BTW, if you use MSYS2 gcc distribution, they have libusb-compat-0.1 which is different from libusb-win32 project. But that may be good enough for you. And you can use WinUSB driver in that case.
