### ISSUE TITLE
If I should make my code open source under GPLv3?

### ISSUE THREAD

**Issue by jdzyzh** [mcuee/libusb-win32#34]
hi，
    I develop my app, while my app is using libusb-win32 driver by systemcall which provide by windows, then should I make my app as open source under GPLv3?

**Comment by mcuee** [comment]
What do you mean by Systemcall?

If you use the library API (libusb0.dll) or if you directly talk to the driver using IOCTL, and you DO NOT change the driver, then you do not need to make your application open source under GPLv3.
https://github.com/mcuee/libusb-win32/blob/master/libusb/src/driver/driver_api.h

What you need to do is to fulfill the GPLv3 obligation by provide the link to this repo and mention that you are using this libusb-win32 driver (GPLv3).
