### ISSUE TITLE
zadig 2.8 does not work on sony A7iv when updating to Ver 2.01 

### ISSUE THREAD

**Issue by ASASS568** [mcuee/libusb-win32#48]
zadig 2.8 does not work on sony A7iv when updating to Ver 2.01 
![278871327-0f35a3f7-fa79-42e6-8a88-e2bee0405944](https://github.com/mcuee/libusb-win32/assets/149306815/ae55ba30-2f17-4f1e-878d-132832cff62f)

**Comment by mcuee** [comment]
Please file an issue with libwdi/Zadig. That is a different project.
https://github.com/pbatard/libwdi

**Comment by mcuee** [comment]
BTW, please do not just use a screentshot to report the issue. Please provide some details of the issue and why you think it is a libusb-win32 issue.

For example, I have no idea of which app is at Version 2.01 here.
